image: node:latest

# Pipeline
stages:
  - install
  - build
  - exercise
  - test

variables:
   npm_config_cache: "$CI_PROJECT_DIR/.npm"
   CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
   key:
     files:
        - movies/package.json
   paths:
      - movies/.npm
      - movies/cache/Cypress
      - movies/node_modules
      - movies/build
      


# Jobs 
install_dependencies:
  stage: install
  script:
    - cd movies
    - npm ci --cache .npm --prefer-offline
  artifacts:
    paths:
      - movies/node_modules/

bundle_app:
  stage: build
  script:
    - cd movies
    - npm run build

exercise_job:
  stage: exercise
  script:
    - echo "Run exercise job"
  only:
    - main

e2etest:
# Node docker image with Cypress and Chrome pre-installed
  stage: test
  image:  cypress/browsers:node18.12.0-chrome106-ff106
  script:
  - cd movies
  - echo "Run tests in headless mode"
  - npx serve -s ./build  -l 3000  &
  - CYPRESS_CACHE_FOLDER="$CI_PROJECT_DIR/cache/Cypress" npx cypress install
  - npx cypress run --browser chrome 


